Adding RFE Pipelines Helm Chart
redhat-cop/rhel-edge-automation-arch pull request #159
Opened 2021-11-02 17:59 UTC by jordigilh

Adds the RFE Pipelines helm chart.  The annotation, namespace and labels are the only fields that have been parametrized.
 
```yaml
metadata:
  annotations:
  {{- range $key, $value := .Values.pipelines.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }} 
```

The other parts of the manifests remain unchanged.
@sabre1041 @nasx can you take a look and let me know what you think?

2021-11-02 22:57 UTC, sabre1041 commented
Thanks @jordigilh 

You can use the following instead of having to perform the iteration of annotations to simplify the logic

```
{{ toYaml .Values.pipelines.annotations | nindent 4 }}
```

2021-11-03 13:09 UTC, jordigilh commented
> Thanks @jordigilh
> 
> You can use the following instead of having to perform the iteration of annotations to simplify the logic
> 
> ```
> {{ toYaml .Values.pipelines.annotations | nindent 4 }}
> ```

Done.

2021-11-08 14:54 UTC, jordigilh commented
@sabre1041 @nasx any further comments? Otherwise, can we merge this PR?

2021-11-08 14:58 UTC, sabre1041 commented
@jordigilh im ok. there are plenty of areas of where additional variables can be included in this chart, but can be a followup task

2021-11-09 06:38 UTC, sabre1041 requested changes

2021-11-09 06:38 UTC, sabre1041 commented on charts/rfe-pipelines/values.yaml
> +    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
This annotation has no effect in ArgoCD Helm charts

2021-11-09 06:38 UTC, sabre1041 commented on charts/rfe-pipelines/values.yaml
> +    argocd.argoproj.io/sync-wave: "5"
The analogous annotation for Helm is `helm.sh/hook-weight`

2021-11-09 13:39 UTC, jordigilh commented on charts/rfe-pipelines/values.yaml
> +    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
I'll remove it.

2021-11-09 14:18 UTC, jordigilh commented on charts/rfe-pipelines/values.yaml
> +    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
Done.

2021-11-09 14:22 UTC, jordigilh commented on charts/rfe-pipelines/values.yaml
> +    argocd.argoproj.io/sync-wave: "5"
Do you think it's worth this annotation? It will be applied to all manifests in the chart. Is it OK if I remove it?

2021-11-13 02:06 UTC, sabre1041 commented
@jordigilh are you planning on incorporating the `Subscription` into this chart?

2021-11-13 02:08 UTC, jordigilh commented
> @jordigilh are you planning on incorporating the `Subscription` into this chart?

Was not planning, but I can add it. What do you think?

2021-11-13 02:12 UTC, sabre1041 commented
> > @jordigilh are you planning on incorporating the `Subscription` into this chart?
> 
> Was not planning, but I can add it. What do you think?

Personally... im almost feeling like we want to just keep the Subscriptions etc completely separate. Mainly because of the baseline complexities working with the OLM. @nasx interested in your thoughts so we can provide the best path forward. Having the generic operator chart makes it possible to manage the lifecycles separately.

2021-11-22 06:10 UTC, sabre1041 approved these changes
LGTM

2021-11-22 06:10 UTC, merged