Added gitops-oauth Helm Chart
redhat-cop/rhel-edge-automation-arch pull request #161
Opened 2021-11-05 02:20 UTC by jordigilh

Defines the helm chart that contains the OAuth job responsible for merging the different OAuth providers required to operate ArgoCD.

In order to be able to provide generic providers, the PR proposes the solution of appending the different manifests to the `rfe-oauth` secret as individual files, so that when the secret is mounted to a path, the script can simply iterate over each of the `.json` files in the mounted path and call the python script for each individual file.

@sabre1041 @nasx please review at your discretion.

2021-11-05 21:45 UTC, sabre1041 requested changes

2021-11-05 21:45 UTC, sabre1041 commented on charts/oauth/templates/merge-oauth-identity-provider-configmap.yaml
> +  namespace: {{ .Values.namespace}}
This should use `.Release.Namespace`

2021-11-05 21:45 UTC, sabre1041 commented on charts/oauth/templates/merge-oauth-identity-providers-job.yaml
> +  namespace: {{ .Values.namespace}}
This should use `.Release.Namespace`

2021-11-05 21:45 UTC, sabre1041 commented on charts/oauth/values.yaml
> +  annotations:
These annotations would need to migrate to Helm hooks (does not need to be separated as Values)

2021-11-05 22:04 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-provider-configmap.yaml
> +  namespace: {{ .Values.namespace}}
ack

2021-11-05 22:05 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-providers-job.yaml
> +  namespace: {{ .Values.namespace}}
ack

2021-11-05 22:05 UTC, jordigilh commented on charts/oauth/values.yaml
> +  annotations:
ok, I'll move them back to the job with the equivalent value in helm

2021-11-08 15:44 UTC, jordigilh commented on charts/oauth/values.yaml
> +  annotations:
on a second thought, do you think that having the annotations here makes sense? This is going to be converted into an individual chart. It would make sense if it was wrapped around other manifests so that these are run first.

2021-11-08 16:55 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-provider-configmap.yaml
> +  namespace: {{ .Values.namespace}}
Done

2021-11-08 16:56 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-providers-job.yaml
> +  namespace: {{ .Values.namespace}}
Done. If that's ok with you, I've changed it for all templates in the chart.

2021-11-09 06:43 UTC, sabre1041 requested changes

2021-11-09 06:43 UTC, sabre1041 commented on charts/oauth/templates/merge-oauth-identity-providers-role-rolebinding.yaml
> +  namespace: {{ template "common.names.namespace" $ }}
ClusterRoleBinding are non-namespaced resources

2021-11-09 06:43 UTC, sabre1041 commented on charts/oauth/templates/merge-oauth-identity-providers-role-rolebinding.yaml
> +    namespace: {{ .Release.Namespace }}
Replace with `namespace: {{ template "common.names.namespace" $ }}`

2021-11-09 06:43 UTC, sabre1041 commented on charts/oauth/values.yaml
> +  annotations:
Are these even being used?

2021-11-09 13:23 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-provider-configmap.yaml
> +  namespace: {{ .Values.namespace}}
as discussed, changed to `namespace: {{ template "common.names.namespace" $ }}`

2021-11-09 13:23 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-providers-job.yaml
> +  namespace: {{ .Values.namespace}}
as discussed, changed to `namespace: {{ template "common.names.namespace" $ }}` for this one and the rest of the manifests that have a namespace field.

2021-11-09 13:30 UTC, jordigilh commented on charts/oauth/values.yaml
> +  annotations:
I've tried with and without the annotations and the chart was deployed successfully in both cases, with the job completing successfully. I verified that the oauth manifest contained the htpasswd identity provider. I reckon we can do without them. WDYT?

2021-11-09 13:32 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-providers-role-rolebinding.yaml
> +  namespace: {{ template "common.names.namespace" $ }}
Removed.

2021-11-09 13:32 UTC, jordigilh commented on charts/oauth/templates/merge-oauth-identity-providers-role-rolebinding.yaml
> +    namespace: {{ .Release.Namespace }}
Done.

2021-11-09 13:33 UTC, jordigilh commented
> Are these even being used?
Seems like they were not. I've removed them from `values.yaml`.

2021-11-09 13:37 UTC, jordigilh commented on charts/oauth/values.yaml
> +  annotations:
I've removed them altogether.

2021-11-13 00:31 UTC, sabre1041 requested changes

2021-11-13 00:31 UTC, sabre1041 commented on charts/oauth/values.yaml
> +identityProviders:
`identityProviders` should be an empty list as we dont always want to install the htpasswd provider into every environment

2021-11-13 00:38 UTC, jordigilh commented on charts/oauth/values.yaml
> +identityProviders:
sounds good. Replaced with `{}`

2021-11-14 00:01 UTC, jordigilh commented on charts/oauth/values.yaml
> +identityProviders:
Done, forgot to mention it yesterday.

2021-11-25 22:32 UTC, sabre1041 approved these changes
LGTM

2021-11-25 22:32 UTC, merged