Adding CNV chart with CR and Operator
redhat-cop/rhel-edge-automation-arch pull request #164
Opened 2021-11-11 00:23 UTC by jordigilh

Combines the CNV subscription and hyperconverged CR into a single chart. The chart contains a job whose responsibility is to delay the deployment of the hyperconverged CR until the CSV has reached the Successful state. This is to avoid the situation where the CR is created before the CRD.

@sabre1041 @nasx please review at your discretion.

2021-11-11 01:15 UTC, sabre1041 commented
@jordigilh we might be able to omit the need for a job by using this configuration in the `resourceCustomizations` section of the `ArgoCD` resource

```
    operators.coreos.com/Subscription:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.currentCSV ~= nil and (obj.status.state == "AtLatestKnown" or obj.status.state == "UpgradeAvailable" or obj.status.state == "UpgradePending") then
            hs.status = "Healthy"
            hs.message = "Subcription installed"
            return hs
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for Subscription to complete."
        return hs
```

2021-11-11 16:28 UTC, jordigilh commented
> @jordigilh we might be able to omit the need for a job by using this configuration in the `resourceCustomizations` section of the `ArgoCD` resource
> 
> ```
>     operators.coreos.com/Subscription:
>       health.lua: |
>         hs = {}
>         if obj.status ~= nil then
>           if obj.status.currentCSV ~= nil and (obj.status.state == "AtLatestKnown" or obj.status.state == "UpgradeAvailable" or obj.status.state == "UpgradePending") then
>             hs.status = "Healthy"
>             hs.message = "Subcription installed"
>             return hs
>           end
>         end
>         hs.status = "Progressing"
>         hs.message = "Waiting for Subscription to complete."
>         return hs
> ```

Works great! thanks!. I've removed the job and it's resources and updated the [argocd.yaml](https://github.com/redhat-cop/rhel-edge-automation-arch/blob/653fbc49aa44b30286152cf57c240b3c5eaec518/openshift/gitops/manifests/bootstrap/argocd/base/argocd.yaml#L40-L52) file to include the `resourceCustomizations`.

I've tested it without the helm pre-hooks and works fine as well. So they're gone :smile:

2021-11-11 23:48 UTC, sabre1041 requested changes

2021-11-11 23:48 UTC, sabre1041 commented on openshift/gitops/manifests/bootstrap/argocd/base/argocd.yaml
> +            hs.message = "Subcription installed"
```suggestion
            hs.message = "Subscription installed"
```

2021-11-11 23:51 UTC, sabre1041 requested changes

2021-11-11 23:51 UTC, sabre1041 commented on charts/cnv/templates/subscription.yaml
> +  namespace: {{ .Values.namespace }}
` namespace: {{ template "common.names.namespace" $ }}`

2021-11-11 23:51 UTC, sabre1041 commented on charts/cnv/templates/operatorgroup.yaml
> +  namespace: {{ .Values.namespace }}
` namespace: {{ template "common.names.namespace" $ }}

2021-11-11 23:51 UTC, sabre1041 commented on charts/cnv/templates/kubevirt-hyperconverged.yaml
> +  namespace: {{ .Values.namespace }}
`namespace: {{ template "common.names.namespace" $ }}`

2021-11-11 23:51 UTC, jordigilh commented on openshift/gitops/manifests/bootstrap/argocd/base/argocd.yaml
> +            hs.message = "Subcription installed"
Updated.

2021-11-11 23:52 UTC, sabre1041 commented
@jordigilh This is really exciting! It worked great. we most likely want to add retries, but that can come later. a few small minor changes

2021-11-11 23:54 UTC, jordigilh commented on charts/cnv/templates/kubevirt-hyperconverged.yaml
> +  namespace: {{ .Values.namespace }}
done

2021-11-11 23:54 UTC, jordigilh commented on charts/cnv/templates/operatorgroup.yaml
> +  namespace: {{ .Values.namespace }}
Done

2021-11-11 23:54 UTC, jordigilh commented on charts/cnv/templates/subscription.yaml
> +  namespace: {{ .Values.namespace }}
Done and removed the `namespace` field in the `values.yaml` file.

2021-11-12 00:03 UTC, sabre1041 approved these changes
LGTM!

2021-11-12 00:03 UTC, merged