Adding Quay chart with subscription
redhat-cop/rhel-edge-automation-arch pull request #165
Opened 2021-11-12 20:59 UTC by jordigilh

Adds the subscription to the quay chart and also defines a template for the app-manager to trigger the quay chart deployment.

@sabre1041 I have not been able to test this in my environment due to dependencies in the quay deployment. If you can test it in your environment, please give it a try and let me know how it goes.

/Jordi

2021-11-12 22:46 UTC, sabre1041 requested changes

2021-11-12 22:46 UTC, sabre1041 commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
the `quay` namespace is specified here, but no `Namespace` resource is provided. Are we assuming one will be there already? I would say yes, but confirming. Also, this variable should be externalized

2021-11-12 22:47 UTC, sabre1041 commented
@jordigilh my testing failed. I do not see a `Subscription` resource being generated.

2021-11-12 22:50 UTC, jordigilh commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
hmm I thought the `CreateNamespace` would take care of it, but in short it only cares for the destination namespace in the `Application` manifest. I'll add the Namespace resource to the chart.

2021-11-12 22:50 UTC, sabre1041 commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
It eventually fails because the `QuayRegistry` resource is not found

2021-11-12 22:51 UTC, sabre1041 commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
@jordigilh we arent installing into the `quay` namesapce

2021-11-12 22:51 UTC, jordigilh commented
> @jordigilh my testing failed. I do not see a `Subscription` resource being generated.

ok thanks for testing it.

2021-11-12 22:53 UTC, jordigilh commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
Where then?

2021-11-13 00:23 UTC, sabre1041 commented
@jordigilh You are missing the annotations on the `QuayRegistry` resource. The changes that you made were applied to the old `Kustomize` resources and not the one in the Helm chart

2021-11-13 00:31 UTC, jordigilh commented on openshift/gitops/manifests/configs/quay/base/quayregistry.yaml
>    namespace: quay
Changes reverted. This file should have not been included in the PR.

2021-11-13 02:05 UTC, sabre1041 approved these changes
LGTM

2021-11-13 02:05 UTC, merged