Adding HTTPD chart
redhat-cop/rhel-edge-automation-arch pull request #167
Opened 2021-11-15 14:06 UTC by jordigilh

Adds the httpd manifests found here in a helm chart. I've parametrized the docker image name, currently `httpd-2.4` and the image stream tag, currently `httpd:2.4-el8`, to make it easier to update in the future. 

@sabre1041 @nasx please take a look.

2021-11-16 06:44 UTC, sabre1041 requested changes

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      FROM registry.redhat.io/rhel8/{{ .Values.buildConfig.source.dockerFileFrom.name }}
when an `ImageStreamTag` is provided as an input, the `FROM` field is automatically overwritten. So it really do not matter in the end what the value is here

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +        subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms --enable rhel-8-for-x86_64-appstream-rpms && \
Note for later that we might want to allow these repositories to be dynamically overridden

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      name: httpd-ostree:latest
Do we want to extract this out to a value. It could drive this variable along with the trigger annotation on the `Deployment`

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +  namespace: rfe
Replace with `{{ template "common.names.namespace" $ }}`

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/deployment.yaml
> +  namespace: rfe
Replace with `{{ template "common.names.namespace" $ }}`

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/route.yaml
> +spec:
`namespace` is missing and should be `{{ template "common.names.namespace" $ }}`

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/pvc.yaml
> +  namespace: httpd
`namespace` should be `{{ template "common.names.namespace" $ }}`

2021-11-16 06:44 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-imagestream.yaml
> +  namespace: rfe
Replace with `{{ template "common.names.namespace" $ }}`

2021-11-16 15:07 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      FROM registry.redhat.io/rhel8/{{ .Values.buildConfig.source.dockerFileFrom.name }}
Understood. I'll revert the change.

2021-11-16 15:14 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +        subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms --enable rhel-8-for-x86_64-appstream-rpms && \
Will move repos to `values.yaml`.

2021-11-16 15:15 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      name: httpd-ostree:latest
I'll move it out to `values.yaml` and update the trigger annotation in the `Deployment`.

2021-11-16 15:19 UTC, jordigilh commented on charts/httpd/templates/deployment.yaml
> +  namespace: rfe
ack.

2021-11-16 15:24 UTC, jordigilh commented on charts/httpd/templates/route.yaml
> +spec:
Done

2021-11-16 15:24 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      FROM registry.redhat.io/rhel8/{{ .Values.buildConfig.source.dockerFileFrom.name }}
Done.

2021-11-16 15:24 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +        subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms --enable rhel-8-for-x86_64-appstream-rpms && \
Done.

2021-11-16 15:25 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +      name: httpd-ostree:latest
Done.

2021-11-16 15:25 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +  namespace: rfe
Done.

2021-11-16 15:25 UTC, jordigilh commented on charts/httpd/templates/deployment.yaml
> +  namespace: rfe
Done.

2021-11-16 15:25 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-imagestream.yaml
> +  namespace: rfe
Done.

2021-11-19 06:57 UTC, sabre1041 requested changes

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/deployment.yaml
> +    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.buildConfig.output.imageStreamTagName }}","namespace":"{{- template "common.names.namespace" $ }}"},"fieldPath":
The `namespace` here should be able to be defined and distinctly separate from the `namespaceOverride` which controls other resources itself. If defined, use the desired value. Otherwise, default to the current namespace

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-imagestream.yaml
> +  name: httpd-ostree
Extract out to a variable

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +  name: httpd-ostree
Extract out to a variable

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/deployment.yaml
> +  name: httpd
Use common chart name

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/route.yaml
> +  name: httpd
Use common chart name

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/pvc.yaml
> +  name: httpd
Use common chart name

2021-11-19 06:57 UTC, sabre1041 commented on charts/httpd/templates/service.yaml
> +  name: httpd
Use common chart name

2021-11-23 02:23 UTC, jordigilh commented on charts/httpd/templates/deployment.yaml
> +    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.buildConfig.output.imageStreamTagName }}","namespace":"{{- template "common.names.namespace" $ }}"},"fieldPath":
isn't this field pointing to the namespace where the imagestream is deployed? If so, shouldn't this logic be applied to the namespace of the imagestream?

2021-11-23 02:28 UTC, jordigilh commented on charts/httpd/templates/route.yaml
> +  name: httpd
Will do. Also, changing the name of the route to something than `httpd` will impact the oci upload task:
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/fb79ec9f234db36d1f038c4332b9f678904c706e/ansible/roles/oci-publish-content/tasks/main.yaml#L23
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/fb79ec9f234db36d1f038c4332b9f678904c706e/ansible/roles/oci-publish-content/tasks/main.yaml#L49

2021-11-23 02:34 UTC, jordigilh commented on charts/httpd/templates/pvc.yaml
> +  name: httpd
Done.

2021-11-23 02:35 UTC, jordigilh commented on charts/httpd/templates/service.yaml
> +  name: httpd
Done, used `{{ template "common.names.fullname" . }}`

2021-11-23 02:35 UTC, jordigilh commented on charts/httpd/templates/deployment.yaml
> +  name: httpd
Done. Used `{{ template "common.names.fullname" . }}`.

2021-11-23 02:35 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-buildconfig.yaml
> +  name: httpd-ostree
Done.

2021-11-23 02:35 UTC, jordigilh commented on charts/httpd/templates/httpd-ostree-imagestream.yaml
> +  name: httpd-ostree
Done.

2021-11-23 06:29 UTC, sabre1041 commented on charts/httpd/templates/deployment.yaml
> +    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.buildConfig.output.imageStreamTagName }}","namespace":"{{- template "common.names.namespace" $ }}"},"fieldPath":
Let's keep it as is. We can revisit it as part of a next pass if necessary

2021-11-24 18:59 UTC, sabre1041 approved these changes
LGTM

2021-11-24 18:59 UTC, merged