Adding image-builder-vm chart
redhat-cop/rhel-edge-automation-arch pull request #171
Opened 2021-11-15 18:29 UTC by jordigilh

Adds the image-builder-vm charts.

@sabre1041 @nasx please review.

2021-11-26 05:18 UTC, sabre1041 requested changes

2021-11-26 05:18 UTC, sabre1041 commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +            url: 'http://nexus:8081/repository/rfe-rhel-media/rhel-8.5-x86_64-kvm.qcow2'
This location needs to account with the version that we are using. We should also externalize it as well into a variable

2021-11-26 05:18 UTC, sabre1041 commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +        os.template.kubevirt.io/rhel8.3: 'true'
8.3?

2021-11-26 05:18 UTC, sabre1041 commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +          type: pc-q35-rhel8.2.0
8.2?

2021-11-26 05:18 UTC, sabre1041 commented on charts/image-builder-vm/values.yaml
> +    os.template.kubevirt.io/rhel8.3: 'true'
8.3?

2021-11-29 13:27 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +        os.template.kubevirt.io/rhel8.3: 'true'
I'll move it out to `values.yaml` and make sure it's aligned with the iso version.

2021-11-29 13:41 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +          type: pc-q35-rhel8.2.0
From what I can gather, the postfix `rhel8.2.0` is more informative than anything else.
https://github.com/kubevirt/kubevirt/blob/debf29e7bf0df011248b3662c46bfa55cf3f6750/pkg/virt-config/virt-config.go#L46

From what I can see in the kubevirt code, as long as it has prefix `pc-q35` or just `q35` it will be sufficient to resolve to amd64 arch.

I can change it to `rhel8.5.0` but I'd be in favor of trimming it to just `pc-q35`, unless @nasx has any objection. WDYT?

2021-11-29 13:42 UTC, jordigilh commented on charts/image-builder-vm/values.yaml
> +    os.template.kubevirt.io/rhel8.3: 'true'
Will extract and sync with the rhel version we use for the QCOW2.

2021-11-29 14:08 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +            url: 'http://nexus:8081/repository/rfe-rhel-media/rhel-8.5-x86_64-kvm.qcow2'
I'll move it out.

2021-11-29 15:51 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +            memory: 4Gi
@nasx Can we reduce the memory footprint for the RHEL VM from `16Gi` to `4Gi`? I have been able to boot RHEL with just `4Gi` and it would be great if we can reduce the memory requirements for this VM. WDYT?

2021-11-29 15:52 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +            url: 'http://nexus:8081/repository/rfe-rhel-media/rhel-8.5-x86_64-kvm.qcow2'
I've extracted the RHEL version but left the image and path in the manifest. I am not sure if it's worth extracting it all for now, but let me know if you want me to take that extra step :smile:

2021-11-29 15:54 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +        os.template.kubevirt.io/rhel8.3: 'true'
Done. I'm using a combination of a template and the values to generate this label.
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/964e0746a56cb746d564c29636550b2174ee446f/charts/image-builder-vm/templates/_helpers.tpl#L4-L6
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/964e0746a56cb746d564c29636550b2174ee446f/charts/image-builder-vm/templates/image-builder-vm.yaml#L12

2021-11-29 15:56 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +          type: pc-q35-rhel8.2.0
I ended up extracting the RHEL version to `values.yaml` file and I use it here.
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/964e0746a56cb746d564c29636550b2174ee446f/charts/image-builder-vm/templates/image-builder-vm.yaml#L71

2021-11-29 15:56 UTC, jordigilh commented on charts/image-builder-vm/values.yaml
> +    os.template.kubevirt.io/rhel8.3: 'true'
Done.

2021-12-01 00:16 UTC, jordigilh commented on charts/image-builder-vm/templates/image-builder-vm.yaml
> +          type: pc-q35-rhel8.2.0
the latest version is `pc-q35-rhel8.4.0`, so I've "upgraded" and parametrized it.

2021-12-09 00:24 UTC, nasx approved these changes
LGTM

2021-12-09 00:24 UTC, merged