Adding Group Sync operator helm chart
redhat-cop/rhel-edge-automation-arch pull request #172
Opened 2021-11-15 19:12 UTC by jordigilh

Adds the group-sync operator. I've modified the operator chart to add the ability to specify extra configuration and define annotations in the `OperatorGroup` to match the current manifest specification for the group-sync operator:

https://github.com/redhat-cop/rhel-edge-automation-arch/blob/1588add318c58880b6e35c1a0b90d5283ffeb030/openshift/gitops/clusters/overlays/shared/configs/auth/group-sync-operator-operatorgroup.yaml#L4-L5

and 

https://github.com/redhat-cop/rhel-edge-automation-arch/blob/1588add318c58880b6e35c1a0b90d5283ffeb030/openshift/gitops/clusters/overlays/shared/configs/auth/group-sync-operator-subscription.yaml#L12-L15

@sabre1041 @nasx please review.

2021-11-19 07:25 UTC, sabre1041 requested changes

2021-11-19 07:25 UTC, sabre1041 commented on helm/testing/operators/group-sync-operator.yaml
> +# install to nexus namespace
Group Sync Operator should be installed to a new namespace called `group-sync-operator`

2021-11-19 07:25 UTC, sabre1041 commented on helm/testing/operators/group-sync-operator.yaml
> +  - name: WATCH_NAMESPACE
The operator has not been tested with this configuration

2021-11-19 07:25 UTC, sabre1041 commented on charts/operator/templates/subscription.yaml
> +  {{- .Values.config  | toYaml | nindent 4 -}}
Can we replace with `{{- tpl (toYaml .Values.config) $ | nindent 4 }}`?

2021-11-19 07:25 UTC, sabre1041 commented on helm/testing/operators/group-sync-operator.yaml
> +    olm.providedAPIs: GroupSync.v1alpha1.redhatcop.redhat.io
This will get added automatically by the OLM

2021-11-23 02:16 UTC, jordigilh commented on helm/testing/operators/group-sync-operator.yaml
> +  - name: WATCH_NAMESPACE
This configuration has been carried over from the original manifest:
https://github.com/redhat-cop/rhel-edge-automation-arch/blob/fb79ec9f234db36d1f038c4332b9f678904c706e/openshift/gitops/clusters/overlays/shared/configs/auth/group-sync-operator-subscription.yaml#L13-L15

Let me know if you want me to remove it for the chart.

2021-11-23 02:18 UTC, jordigilh commented on helm/testing/operators/group-sync-operator.yaml
> +# install to nexus namespace
Done. I've replaced `nexus` for `group-sync-operator`.

2021-11-23 02:18 UTC, jordigilh commented on charts/operator/templates/subscription.yaml
> +  {{- .Values.config  | toYaml | nindent 4 -}}
Done.

2021-11-23 02:18 UTC, jordigilh commented on helm/testing/operators/group-sync-operator.yaml
> +    olm.providedAPIs: GroupSync.v1alpha1.redhatcop.redhat.io
Removed.

2021-11-25 18:09 UTC, sabre1041 requested changes
LGTM

2021-11-25 18:09 UTC, sabre1041 approved these changes

2021-11-25 18:09 UTC, merged