Fix/quay namespace mismatch
redhat-cop/rhel-edge-automation-arch pull request #179
Opened 2021-11-19 15:20 UTC by jordigilh

* Pins Quay CR to `quay` namespace.
* Updates quay subscription to `stable-3.6`.
* Pins `quay-setup` job and related role and rolebinding to the `rfe` namespace.

@sabre1041 @nasx let me know what you think about this.

2021-11-19 18:52 UTC, sabre1041 requested changes
One small change and then we should be good

2021-11-19 18:52 UTC, sabre1041 commented on charts/quay/templates/rfe-automation-rolebinding-quay.yaml
>      name: rfe-automation
This should be extracted to a variable

2021-11-19 19:57 UTC, jordigilh commented on charts/quay/templates/rfe-automation-rolebinding-quay.yaml
>      name: rfe-automation
ack

2021-11-19 20:04 UTC, jordigilh commented on charts/quay/templates/rfe-automation-rolebinding-quay.yaml
>      name: rfe-automation
Done

2021-11-21 02:04 UTC, jordigilh commented
I think this one is ready to be merged. I am getting some consistency in the deployment, barring any network issue from ansible to fetch libraries.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/quay
    repoURL: https://github.com/jordigilh/rhel-edge-automation-arch.git
    targetRevision: fix/quay_namespace_mismatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
In case you want to test it first.

2021-11-21 17:59 UTC, sabre1041 approved these changes
LGTM

2021-11-21 17:59 UTC, merged