[WIP] - Documentation Updates for Helm Migration
redhat-cop/rhel-edge-automation-arch pull request #206
Opened 2021-12-20 22:11 UTC by nasx

2021-12-21 03:49 UTC, sabre1041 requested changes
This looks fantastic! Suggestions included

2021-12-21 03:49 UTC, sabre1041 commented on README.md
>  | Pool ID                      | Pool ID use to map the appropriate subscription to the Image Builder VM |
```suggestion
| Pool ID                      | Red Hat Subscription Manager Pool ID use to map the appropriate subscription to the Image Builder VM |
```

2021-12-21 03:49 UTC, sabre1041 commented on README.md
>  | Pool ID                      | Pool ID use to map the appropriate subscription to the Image Builder VM |
Should we also look at needing to support RH Satellite in the future?

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +global:
We can omit the use of the `global` values

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +The rest of the values will be defined in a Helm values file. In the root of the repository, create a file called `local/bootstrap.yaml` and add the following:
Potential thoughts for where to place values files. Maybe have top level folder called `values` and then subdirectories of `local` and `examples`?

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +Be sure to change the values of `offlineToken`, `poolId`, `username`, and `password`. If you are not sure how to generate an offline token for the Red Hat API, it is documented [here](https://access.
```suggestion
Be sure to change the values of `offlineToken`, `poolId`, `username`, and `password` to match the details for your account. If you are not sure how to generate an offline token for the Red Hat API, it is documented [here](https://access.redhat.com/articles/3626371#bgenerating-a-new-offline-tokenb-3).
```

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +Helm and Argo CD are used to deploy and manage all of the project components. From a high level, a Helm chart called `application-manager` is used to dynamically build nested app of apps pattern in A
Do we want to link directory to the `applicaton-manager` chart?

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +If you want to disable the deployment/management of certain components (for example, if you want to bring your own cluster that has ODF already installed), each set `disabled: true` in the chart's va
```suggestion
If you want to disable the deployment/management of certain components (for example, if you want to bring your own cluster that has ODF already installed), set `disabled: true` in the chart's values file. For example, to disable ODF, create the following file in `local/disable-odf.yaml`:
```

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +Each chart in the `charts/` directory has a default values file. These values can be overwritten using the same pattern shown above in _Disabling Components_.
Include a relative link to the _Disabling Components_ header

2021-12-21 03:49 UTC, sabre1041 commented on README.md
> +For example, to enable processor emulation for OpenShift Virtualization set `useEmulation: true` in the chart's values file. Store the following file in `local/cnv-processor-emulation.yaml`:
```suggestion
For example, to enable processor emulation for OpenShift Virtualization, set `useEmulation: true` in the chart's values file. Store the following file in `local/cnv-processor-emulation.yaml`:
```

2021-12-21 14:51 UTC, jordigilh commented on README.md
> +Before beginning, make sure you have the latest versions of `oc`/`kubectl`, `git` and `helm` clients installed.
Do we need to mention `tkn` too?
https://tekton.dev/docs/cli/

2021-12-21 14:53 UTC, jordigilh commented on README.md
> +OpenShift can be used to host all of the above site components. These components include:
Nitpick: I'd use stronger words here since we're very much dependent on OCP and RHEL.

2021-12-21 14:53 UTC, nasx commented on README.md
> +Before beginning, make sure you have the latest versions of `oc`/`kubectl`, `git` and `helm` clients installed.
Yeah I'll add that.

2021-12-21 14:54 UTC, nasx commented on README.md
> +OpenShift can be used to host all of the above site components. These components include:
I can reword that. The intent was to show that you can BYO some of the components but that is not clear here.

2021-12-21 14:57 UTC, jordigilh commented on README.md
> +The rest of the values will be defined in a Helm values file. In the root of the repository, create a file called `local/bootstrap.yaml` and add the following:
s/values/config?

2021-12-21 15:28 UTC, jordigilh commented on README.md
> +
Should we mention to wait until the `rfe-gitops` namespace has finished reconciliation before progressing to the next step? Helm will fail to install the Application manifests until the CRD coming from the ArgoCD subscription has been created in the cluster. WDYT?

2021-12-21 15:30 UTC, jordigilh commented on README.md
What about adding at the end of the installation a screenshot of the ArgoCD apps synchronized as an example of the expected outcome from the helm upgrade command?

2021-12-21 16:12 UTC, jordigilh commented on README.md
Or this perhaps:
```bash
$> oc get app -n rfe-gitops
NAME                       SYNC STATUS   HEALTH STATUS
ansible-rfe-runner         Synced        Healthy
catalog-sources            Synced        Healthy
cluster-configs            Synced        Healthy
cnv                        Synced        Healthy
cnv-operator               Synced        Healthy
httpd                      Synced        Healthy
image-builder-vm           Synced        Healthy
namespaces                 Synced        Healthy
nexus                      Synced        Healthy
nexus-operator             Synced        Healthy
operators                  Synced        Healthy
pipelines-operator         Synced        Healthy
quay                       Synced        Healthy
quay-operator              Synced        Healthy
rbac                       Synced        Healthy
resource-locker-operator   Synced        Healthy
rfe                        Synced        Healthy
rfe-automation             Synced        Healthy
rfe-pipelines              Synced        Healthy
user-mgmt                  Synced        Healthy
user-workload-monitoring   Synced        Healthy
```

2021-12-21 18:16 UTC, sabre1041 commented on README.md
If we change the name of any of the apps in the future or add/remove, it will quickly get out of sync

2021-12-21 18:23 UTC, nasx commented on README.md
> +## Above Site Components
I removed a section in the first paragraph about this repository being a work in progress. Should I add that back in but change the wording to show the above site has matured and focus will shift to below site in future releases?

2021-12-21 18:24 UTC, nasx commented on README.md
> +Before beginning, make sure you have the latest versions of `oc`/`kubectl`, `git` and `helm` clients installed.
ACK

2021-12-21 19:37 UTC, nasx commented on README.md
How about we meet in the middle? Add a step to validate all applications in the `rfe-gitops` namespace should be Synced/Healthy?

2021-12-21 19:39 UTC, jordigilh commented on README.md
Yep, that should do it.

2021-12-21 19:45 UTC, jordigilh commented on README.md
You could even go further and just check for the status of the ref-automation app only... since they all derive from it.

2021-12-22 01:44 UTC, nasx commented on README.md
>  | Pool ID                      | Pool ID use to map the appropriate subscription to the Image Builder VM |
Yeah, we have an old issue (#63) for Image Builder tracking this. In the before times there were issues getting Satellite backed repos working with Image Builder. I'm fairly certain those have all been resolved now, so we need to dig that back up.

2021-12-22 01:49 UTC, nasx commented on README.md
> +The rest of the values will be defined in a Helm values file. In the root of the repository, create a file called `local/bootstrap.yaml` and add the following:
+1 on values/{local,examples}

2021-12-22 06:44 UTC, sabre1041 commented on README.md
> +
Doesn't [this](https://github.com/redhat-cop/rhel-edge-automation-arch/blob/helm-migration/setup/init.sh#L12) accomplish what you are asking for?

2021-12-22 13:59 UTC, nasx commented on README.md
> +The rest of the values will be defined in a Helm values file. In the root of the repository, create a file called `local/bootstrap.yaml` and add the following:
As discussed settling on `examples/values` pattern.

2021-12-22 14:01 UTC, sabre1041 commented on README.md
> +## Above Site Components
lets remove the work in progress. we have a solid above site implementation that can be run as is at this time.

We can leave the below site assets until we get there.

2021-12-22 15:54 UTC, sabre1041 approved these changes
LGTM

2021-12-22 16:02 UTC, merged