Add OpenShift Ingress CA to Image Builder VM Trust Store
redhat-cop/rhel-edge-automation-arch pull request #229
Opened 2022-01-18 23:30 UTC by nasx

Resolves issue #226

2022-01-18 23:35 UTC, jordigilh commented on ansible/roles/image-builder/tasks/main.yaml
> +- fail:
Do we need this?

2022-01-18 23:53 UTC, nasx commented on ansible/roles/image-builder/tasks/main.yaml
> +- fail:
No, weird that it shows up. Was removed in a later commit.

2022-01-18 23:56 UTC, jordigilh commented on ansible/roles/image-builder/tasks/main.yaml
> +- fail:
Maybe it shows because I was looking at that specific commit. I don't see it when I browse all the commits. Ignore it :smile:

2022-01-18 23:56 UTC, jordigilh commented
LGTM

2022-01-19 07:11 UTC, ygalblum commented on ansible/roles/image-builder/tasks/main.yaml
> +    ingress_controller_tls_secret_name: "{{ ingress_controller.resources[0].spec.defaultCertificate.name }}"
Is it guaranteed that there will be a defaultCertificate? I ran this query in my cluster and it didn't. So, either I have an issue in my setup (possible), or it is not guaranteed. If it is the latter case, then this step should reflect this possibility and the rest of the new steps should be put into a block that runs only when the defaultCertificate exists

2022-01-19 15:45 UTC, sabre1041 requested changes

2022-01-19 15:45 UTC, sabre1041 commented on ansible/roles/image-builder/tasks/main.yaml
> +    ingress_controller_tls_secret_name: "{{ ingress_controller.resources[0].spec.defaultCertificate.name }}"
There should be considerations of whether the `defaultCertificate` is defined on the `IngressController` resource and if not found, retrieve the secret from the `router-certs-<ingress-name>`

2022-01-19 20:53 UTC, nasx commented on ansible/roles/image-builder/tasks/main.yaml
> +    ingress_controller_tls_secret_name: "{{ ingress_controller.resources[0].spec.defaultCertificate.name }}"
I'm going to revise this to include the following:

1. `defaultCertificate` from `IngressController` resource if it exists
2. `trustedCA` from `Proxy` resource if it exists
3. `router-ca` Secret in `openshift-ingress-operator` namespace

Will consolidate certs from all three sources and inject in Image Builder VM.

2022-01-25 03:42 UTC, sabre1041 approved these changes
LGTM

2022-01-25 03:43 UTC, merged