Update Quay to 3.6
redhat-cop/rhel-edge-automation-arch pull request #230
Opened 2022-01-19 21:39 UTC by sabre1041

Update Quay to 3.6

2022-01-24 21:19 UTC, nasx requested changes

2022-01-24 21:19 UTC, nasx commented on charts/bootstrap/values.yaml
>                              name: ocs-operator
We should migrate the package manifest name to `odf-operator` as well.

2022-01-25 03:40 UTC, sabre1041 commented on charts/bootstrap/values.yaml
>                              name: ocs-operator
updated

2022-01-25 13:24 UTC, nasx approved these changes
LGTM

2022-01-25 13:24 UTC, merged